@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@URL = http://{{host}}/api

### Get palettes
GET {{URL}}/palettes HTTP/1.1

### Get palettes recommendation
GET {{URL}}/palettes/recommendation HTTP/1.1

{
    "r": 12.12,
    "g": 50.55,
    "b": 112.31
}
